<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_R21</name>
   <tag></tag>
   <elementGuidId>5338614c-504a-419d-86be-ffda7ac5f023</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.popup-headline.rating-heading > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popup-rating-warning']/div[2]/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0da913e3-ce33-427d-81ee-fb49ec32e581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>R21</value>
      <webElementGuid>13350dff-0971-4437-ad7d-3ed33241079b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup-rating-warning&quot;)/div[@class=&quot;popup-float-wrapper popup-alert&quot;]/div[@class=&quot;popup-wrapper&quot;]/div[@class=&quot;popup-inner&quot;]/div[@class=&quot;popup-headline rating-heading&quot;]/span[1]</value>
      <webElementGuid>5b1b327f-556d-49ee-8521-5836551e2c3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup-rating-warning']/div[2]/div/div/div/span</value>
      <webElementGuid>79f3a229-afb8-4b22-9aec-d5efecec1673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[5]/following::span[1]</value>
      <webElementGuid>babedc29-417c-4f4b-9b47-2982b7d3fce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vaccinated Only Hall'])[1]/following::span[1]</value>
      <webElementGuid>b5385098-c5b6-4f11-ab00-01250c84e646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IMPORTANT PLEASE READ'])[1]/preceding::span[2]</value>
      <webElementGuid>36059252-1350-4915-8c19-1b06b7cf3d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please note that this film is rated Restricted 21 for aged 21 and above.'])[1]/preceding::span[2]</value>
      <webElementGuid>fc25c6a6-925a-4dc7-8c9c-5d1fcc4291e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='R21']/parent::*</value>
      <webElementGuid>3813f22a-5eb2-4287-817e-1ef6fb210c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div[2]/div/div/div/span</value>
      <webElementGuid>0bdf539a-756a-4ab9-a5a4-2b1258346f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'R21' or . = 'R21')]</value>
      <webElementGuid>cd818a92-95a5-4788-ad31-057f185f1a79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
