<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Proceed</name>
   <tag></tag>
   <elementGuidId>4c70383c-9a93-4d3d-b52a-bb1e51aa6389</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#seating_confirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='seating_confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8e821d8a-2c59-4ad0-abef-29014d093f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button form-control mid-wide bg-white inline seat-warn-btn</value>
      <webElementGuid>f0a26a4f-383d-495e-9758-75531dec1189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>seating_confirm</value>
      <webElementGuid>b61de6da-e488-4a23-a5b8-1e2f17af706a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed</value>
      <webElementGuid>934445d2-fbbc-4451-ac59-9be79bd7ce7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;seating_confirm&quot;)</value>
      <webElementGuid>bad7f5e4-d5dd-473d-bfc1-46010ba6cfd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='seating_confirm']</value>
      <webElementGuid>4655e590-0efd-4ef9-8f5d-93bbbc0f9215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup-seating-warning']/div[2]/div/div/div[3]/a[2]</value>
      <webElementGuid>b1f11659-ccc5-44cb-aa70-7f1e5cb2fe14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Proceed')]</value>
      <webElementGuid>1b9c2368-82af-49ae-9e7c-9a180dcb8319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Different Rows of Seats'])[1]/following::a[2]</value>
      <webElementGuid>bbb3bfaa-4634-42d6-a849-be311df5d9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exit'])[1]/following::a[2]</value>
      <webElementGuid>d397e679-124d-4930-adc6-64e711bb951c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart Processing Error'])[1]/preceding::a[1]</value>
      <webElementGuid>b2475b88-fd71-43f2-ad50-3a7375c75e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promotion Notice'])[1]/preceding::a[2]</value>
      <webElementGuid>7886859f-11bf-4469-a37e-cde2badac2a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proceed']/parent::*</value>
      <webElementGuid>b8db3449-4cb3-45a0-b751-34d3794857a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div[2]/div/div/div[3]/a[2]</value>
      <webElementGuid>bc30c79c-d332-440e-95c7-a036d67e6298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'seating_confirm' and (text() = 'Proceed' or . = 'Proceed')]</value>
      <webElementGuid>9e133e7f-29e1-488d-acc0-956ab584ae93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
