<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancel</name>
   <tag></tag>
   <elementGuidId>db55c675-6e71-4824-a4d1-3c380151bd00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment-selection-cancel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;select-payment-method&quot;]/div[4]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>043eeb4f-6297-4e6c-97f5-c3844414a27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-selection-cancel</value>
      <webElementGuid>4d40488b-3f43-48e1-b3b2-506514bfb540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bt-a-mybutton bt-bg-black button-cancel-book</value>
      <webElementGuid>999cee4b-801f-44ac-9b71-d75a0aa7d4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>54c20385-a2ef-4752-882a-ad91e6c401c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-selection-cancel&quot;)</value>
      <webElementGuid>25fd9115-b8b0-496f-a963-0c907bc295be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='payment-selection-cancel']</value>
      <webElementGuid>ca7a96a0-deb2-4642-996b-6487526ee53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-payment-method']/a</value>
      <webElementGuid>2b95e8c1-9ba7-4ff2-8ba2-6b5e4c64e762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancel')]</value>
      <webElementGuid>3fcfa694-9c96-4ed8-98da-8edf5fcfa85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amex'])[1]/following::a[1]</value>
      <webElementGuid>52049275-164b-4333-b2aa-fd520523525e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visa/MasterCard'])[1]/following::a[1]</value>
      <webElementGuid>66235110-522c-45cc-b3a7-5d2c1ae13c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PERSONAL'])[1]/preceding::a[1]</value>
      <webElementGuid>7da69592-37b1-4afa-964a-f781cfe52575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AMEX CARD DETAILS'])[1]/preceding::a[1]</value>
      <webElementGuid>d6747094-736a-4e87-b294-c6e18ccc2005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>e848aeb8-1c7d-439f-8bc6-55ecb8d5095e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/a</value>
      <webElementGuid>5e28ba65-972d-4b4b-a0a9-0494af3d835d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'payment-selection-cancel' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>68ea3dee-412f-47a1-91b3-1af31a346399</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
