<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CONTINUE_addon</name>
   <tag></tag>
   <elementGuidId>34c56875-9d69-4bb7-b836-321b7c56b57a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddToOnePageAddon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;addToOnePageAddon&quot;]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dab51a70-98e8-4853-bab3-f9e68e8dd7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-custom text-uppercase btn-checkout mar-top-1</value>
      <webElementGuid>104bf297-9a70-487e-b699-2702e99eee85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddToOnePageAddon</value>
      <webElementGuid>5e894a2b-eecf-4960-b00c-d59f54db3bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTINUE</value>
      <webElementGuid>a7151971-6547-4c63-8643-3ffc311f47b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddToOnePageAddon&quot;)</value>
      <webElementGuid>d27b510a-ded1-4a8e-bd1d-d1f25f3bd368</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='AddToOnePageAddon']</value>
      <webElementGuid>bf68ac32-bc27-4b3b-89d6-af35bca8a577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'CONTINUE')])[2]</value>
      <webElementGuid>82435051-41cb-4a9d-8ced-14d7322831be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[2]/following::a[1]</value>
      <webElementGuid>9cc04617-fe64-4b9b-981d-8b3f31ad0fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular Popcorn Combo'])[1]/following::a[3]</value>
      <webElementGuid>1e589555-3336-4301-b6c5-b67350af9005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD-ONS'])[2]/preceding::a[1]</value>
      <webElementGuid>2e451ea6-bdac-454b-84d5-7c6500eb8c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAYMENT'])[1]/preceding::a[2]</value>
      <webElementGuid>ef08f5a2-daf3-41c0-96c8-6fb7174f22aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div/div/a</value>
      <webElementGuid>e987d181-74f6-4b5d-8cb3-c86b441802e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'AddToOnePageAddon' and (text() = 'CONTINUE' or . = 'CONTINUE')]</value>
      <webElementGuid>7a18b639-bfec-4022-b945-716c7e87efb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
