<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CONTINUE</name>
   <tag></tag>
   <elementGuidId>f04b96c3-18b5-439e-94d1-1368cd09164c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddToOnePagePromotions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;promotion&quot;]/div[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>09bb6d6f-f373-46f7-b039-30ce05fd781d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-custom text-uppercase btn-checkout mar-top-1</value>
      <webElementGuid>99c2cf79-65db-4ad7-8d9f-05b31b89b7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddToOnePagePromotions</value>
      <webElementGuid>79a4c5a4-a8f1-4101-998d-e4aabc8a3dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTINUE</value>
      <webElementGuid>d98d1350-ec92-4e28-bfd2-b7958fea8cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddToOnePagePromotions&quot;)</value>
      <webElementGuid>dae20fb3-1464-435a-874e-3a16f7a8cd85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='AddToOnePagePromotions']</value>
      <webElementGuid>7231416d-fb26-4758-ab29-eff92c447c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CONTINUE')]</value>
      <webElementGuid>74bae76b-af63-490b-9ee6-5c5d48820e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONFIRM'])[1]/following::a[1]</value>
      <webElementGuid>0c5bf657-1dc8-4619-b804-7a8d456ddb51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='here'])[1]/following::a[2]</value>
      <webElementGuid>3582a224-ba35-4953-b42e-5280c7fcab92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROMOS'])[2]/preceding::a[1]</value>
      <webElementGuid>195752af-b616-4b43-acfd-a9bc8fa2b3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD-ONS'])[1]/preceding::a[1]</value>
      <webElementGuid>67d5e570-d3d9-47e3-96a8-c1400c0678d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CONTINUE']/parent::*</value>
      <webElementGuid>d71702a8-24d3-4845-b781-50a820c87f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/a</value>
      <webElementGuid>fde0ae63-bd5e-4492-a185-ee0edc08f0ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'AddToOnePagePromotions' and (text() = 'CONTINUE' or . = 'CONTINUE')]</value>
      <webElementGuid>62ff2f38-78c3-4cdf-a500-0e9dab39bb54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
