<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Exit</name>
   <tag></tag>
   <elementGuidId>82492f70-eb64-4c2b-b986-d2699706562c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popup-rating-warning']/div[2]/div/div/div[3]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#popup-rating-warning > div.popup-float-wrapper.popup-alert > div.popup-wrapper > div.popup-inner > div.popup-control > a.button.form-control.mid-wide.bg-red.inline.decline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6da4a5b7-b5eb-4d91-b18c-b54595b51df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button form-control mid-wide bg-red inline decline</value>
      <webElementGuid>d7980284-d8e0-4e53-9815-19693b161742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Showtimes</value>
      <webElementGuid>8f19b193-239f-4471-886d-8ff01a0df07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Exit</value>
      <webElementGuid>479e78ae-7e3a-4acc-86fc-2657bae4929b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup-rating-warning&quot;)/div[@class=&quot;popup-float-wrapper popup-alert&quot;]/div[@class=&quot;popup-wrapper&quot;]/div[@class=&quot;popup-inner&quot;]/div[@class=&quot;popup-control&quot;]/a[@class=&quot;button form-control mid-wide bg-red inline decline&quot;]</value>
      <webElementGuid>420ceb0b-5326-4e7f-97a7-e3f31b04397d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup-rating-warning']/div[2]/div/div/div[3]/a[2]</value>
      <webElementGuid>718f636f-64a6-4108-87a8-d4efd9fe5aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Exit')]</value>
      <webElementGuid>812fe0f9-f8d0-42b9-bda3-86157dd72ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agree'])[1]/following::a[1]</value>
      <webElementGuid>26929528-0a05-4b22-ac16-bc9b914041e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please note that this film is rated M18 - Mature 18 for persons 18 years and above'])[1]/following::a[2]</value>
      <webElementGuid>0da6cde2-0fcf-49b1-9809-4ea3db43e18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Different Rows of Seats'])[1]/preceding::a[1]</value>
      <webElementGuid>09085b92-c84e-4057-bf94-3939668daa66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceed'])[1]/preceding::a[2]</value>
      <webElementGuid>63a82fe4-b87f-44b9-9e4c-be0fe0a3d65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Exit']/parent::*</value>
      <webElementGuid>8335e8e8-1cb0-4bfc-8795-07971d01047b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/Showtimes')])[2]</value>
      <webElementGuid>fb88c0b1-e78e-4a63-9abe-36c59fcef79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div[2]/div/div/div[3]/a[2]</value>
      <webElementGuid>a2e4c922-7a5b-46d7-8513-f29bb17e05aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Showtimes' and (text() = 'Exit' or . = 'Exit')]</value>
      <webElementGuid>e59a79d6-85c2-48e8-b08a-6376352949ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
