<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_RESET</name>
   <tag></tag>
   <elementGuidId>8d8614ab-7fac-4e07-aa00-35e3ab7f4944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='seatLayoutSection']/div[5]/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-reset.btn-reset-booking</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c1655d08-af54-4216-b712-9fc06715257f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-reset btn-reset-booking</value>
      <webElementGuid>3ee1cd7f-6e62-4422-a3e8-68ce16b821d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>12589ee7-103f-480f-8b52-00658fbd8f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RESET</value>
      <webElementGuid>97979c19-b6e8-43d0-9ec4-f8155062068b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;seatLayoutSection&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-right col-lg-7 col-lg-push-5 col-xs-12 col-sm-8 col-sm-push-4 clearfix func-btn&quot;]/div[@class=&quot;clearfix&quot;]/a[@class=&quot;btn btn-reset btn-reset-booking&quot;]</value>
      <webElementGuid>10b7a2ff-33dd-45c2-b972-7f7ace34c35d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='seatLayoutSection']/div[5]/div/div/a[2]</value>
      <webElementGuid>b44282bf-9ec4-4001-94cf-9f7e4c9d787a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'RESET')]</value>
      <webElementGuid>d93602af-0c59-4560-b6cd-162594e7cbd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONFIRM SEAT(S)'])[1]/following::a[1]</value>
      <webElementGuid>47c88540-600c-4894-b352-70cde1eb13bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[2]/following::a[2]</value>
      <webElementGuid>8bc21d73-5464-41fe-9dce-05bd6becd385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEATS'])[2]/preceding::a[1]</value>
      <webElementGuid>7b25257b-fca0-4968-833a-90735fbe9fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TYPE'])[2]/preceding::a[1]</value>
      <webElementGuid>0857fcd3-8884-46f2-93a7-f717478db2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='RESET']/parent::*</value>
      <webElementGuid>e565e732-77c2-4ef7-83b3-f5eb357f197e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[16]</value>
      <webElementGuid>4603df1b-6411-49b2-b808-74c06e21085f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/a[2]</value>
      <webElementGuid>cc424305-5ee8-4a68-a4f1-661ba5c3126a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'RESET' or . = 'RESET')]</value>
      <webElementGuid>63e52fab-20c7-421f-b5d2-1fecd2e3531a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
