<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_QUANTITY                                            3</name>
   <tag></tag>
   <elementGuidId>91136759-c963-4ddf-bf9a-70629a27f915</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;quantity&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.selections</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a6f75513-1cf6-41f1-83c1-405ccb25c6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selections</value>
      <webElementGuid>36cb7b3b-fa6c-420f-8ca5-d6037313fa2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            QUANTITY
                                            3
                                        </value>
      <webElementGuid>ea6da2fa-8148-4ff4-877f-710c7cd9ddbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ticketList&quot;)/div[@class=&quot;col-lg-1 col-sm-1 col-md-1 text-center&quot;]/div[@class=&quot;wrap-content padding-0-mobile add-on-detail&quot;]/div[@class=&quot;selections&quot;]</value>
      <webElementGuid>4ce0e7d2-2928-4d67-9bcf-f1d91b829e04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ticketList']/div[2]/div/div</value>
      <webElementGuid>6670eaa2-0802-4160-a1ab-f0a0936cff17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$14.50'])[1]/following::div[5]</value>
      <webElementGuid>5e97b797-e501-4d69-9d13-c3e808abc489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adult'])[1]/following::div[5]</value>
      <webElementGuid>0ac4a1ae-0c31-421d-9d13-c5f913f6dc16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AMOUNT'])[2]/preceding::div[2]</value>
      <webElementGuid>da2b961a-17f1-4085-990b-5ef8d7c4ecab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div[2]/div/div</value>
      <webElementGuid>3ebe9947-34b0-4607-b956-1ec20dc659fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                            QUANTITY
                                            3
                                        ' or . = '
                                            QUANTITY
                                            3
                                        ')]</value>
      <webElementGuid>7f847665-0a4e-49cb-8860-78d4dbe45f12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
