<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AMEX CARD DETAILS_credit-card-expiry</name>
   <tag></tag>
   <elementGuidId>097600d7-c213-4054-bde0-1149e2e78d4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='amex-payee-expiry']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#amex-payee-expiry</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de1515db-962e-47d3-9c8f-98ea948be3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>308ed50a-edb4-404f-8551-463abd5a8a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Expiry Date (MM/YY)</value>
      <webElementGuid>cf9e01ad-92c7-4141-be38-0218ca164400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-payment</value>
      <webElementGuid>8c8b4b80-8eae-40be-a2c8-ede0f74d3c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>6baa661d-322a-4b7f-906e-b94d8ff2a606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>def3f2e0-2ddc-4be3-8c33-ceac14ed2430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>credit-card-expiry</value>
      <webElementGuid>557a0854-4da0-4c37-8498-ce7cd5b895af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amex-payee-expiry</value>
      <webElementGuid>111845de-032a-4b23-a5c8-0eabeb81b73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amex-payee-expiry&quot;)</value>
      <webElementGuid>2571b11a-4218-492f-a9ed-bea17ab68902</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='amex-payee-expiry']</value>
      <webElementGuid>086dc9f2-b461-43a5-b209-376e4dc2af82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='amex-payment-form']/input[2]</value>
      <webElementGuid>fd454a6a-0075-4e40-b3f3-974aa9895cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/input[2]</value>
      <webElementGuid>4a0112b5-79ca-420f-9097-ba56431e605a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Expiry Date (MM/YY)' and @type = 'tel' and @name = 'credit-card-expiry' and @id = 'amex-payee-expiry']</value>
      <webElementGuid>00745ee7-d40f-4e9f-99d3-967320015855</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
