<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AMEX CARD DETAILS_credit-card-cvv</name>
   <tag></tag>
   <elementGuidId>c484ee46-a5b1-462d-896a-6710872892a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='amex-payee-cvv']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#amex-payee-cvv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ed6bd6d-45a4-4e66-bdae-617c4cb6f5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>51ee05fd-c776-4140-80b5-5747a665d1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CVV2/CVC2/CID</value>
      <webElementGuid>e869a22d-1fe3-4260-8f9b-8017ba62166d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-payment</value>
      <webElementGuid>b5ba9476-ae6b-4d59-9a5a-0b297df721a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3e40a781-ede7-47bb-bc5b-2cc93f71acd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6b701b87-9050-4a95-b44a-3d3a06a8b19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>credit-card-cvv</value>
      <webElementGuid>e447ae60-e11b-44d4-aea4-cc41a29ec24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amex-payee-cvv</value>
      <webElementGuid>4d8d35aa-b14a-4497-9695-718410c88e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amex-payee-cvv&quot;)</value>
      <webElementGuid>e21a3de3-19aa-4b04-a8cd-f57135f42db2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='amex-payee-cvv']</value>
      <webElementGuid>cebbbe35-70e4-4b4e-bc6b-d74541e43c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='amex-payment-form']/input[3]</value>
      <webElementGuid>39a3e369-397e-4561-9949-8e79b36748af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/input[3]</value>
      <webElementGuid>820b9658-130b-4ccb-b27a-a1b30ac78c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'CVV2/CVC2/CID' and @type = 'password' and @name = 'credit-card-cvv' and @id = 'amex-payee-cvv']</value>
      <webElementGuid>9d6e4826-f098-47c1-814e-32694e9c231c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
