<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amex_payee-contact</name>
   <tag></tag>
   <elementGuidId>85828a35-d790-40a3-a0eb-2a62e371fab0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payee-contact']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payee-contact</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac6c11ed-4ff3-4b24-a7b0-faf5acef937b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contact Number</value>
      <webElementGuid>c696b806-7149-4789-ac50-c6ba5531c045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-payment numbers-only</value>
      <webElementGuid>091faa71-7d91-40d9-a602-c9162bb18890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payee-contact</value>
      <webElementGuid>f7de6447-00ad-40ff-bdd0-6a5ff2092917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payee-contact</value>
      <webElementGuid>095eb588-4ace-415c-926e-69abfd7a4fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c90e1b61-bff7-43d8-89dc-100dbe52e988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d8d8555-cb8c-4bac-8ed4-7725ab9cd66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payee-contact&quot;)</value>
      <webElementGuid>22fdeb42-460e-444b-9f68-406382440846</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payee-contact']</value>
      <webElementGuid>7f2f3321-4fe3-4f2a-8f6f-ed9b5755110e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personal-details']/div/input[4]</value>
      <webElementGuid>724a0aca-cfe7-419e-b37c-51a0278b2e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input[4]</value>
      <webElementGuid>0712288b-5d57-4592-ad2d-e2860d29df0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Contact Number' and @name = 'payee-contact' and @id = 'payee-contact' and @type = 'text']</value>
      <webElementGuid>215fc910-f1ca-408e-be2f-7eb75f3e34c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
