<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amex_payee-name</name>
   <tag></tag>
   <elementGuidId>50fc2bd8-fe7b-403b-8b2e-7f6386a12c25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payee-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payee-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa776ae4-70fb-4cab-9791-d3d856ab7741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>9a87475a-15a0-405e-ab4f-1e659ae54e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-payment</value>
      <webElementGuid>385d9248-8042-42dd-bf14-3904e8854835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payee-name</value>
      <webElementGuid>8fc60abf-0764-44ce-96a9-64d6338bb767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payee-name</value>
      <webElementGuid>363410f0-2a4d-44d6-a67e-e6b15ae1d4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d53059a6-c0a8-4103-a024-ed06de3f4044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9a4e279-f4cd-4339-a0b4-41a35b5c33c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payee-name&quot;)</value>
      <webElementGuid>c4fb5545-91fc-4a16-ad33-bdfad6b16e4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payee-name']</value>
      <webElementGuid>7ae44401-0c00-4830-9aba-4a4a49e5ca7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personal-details']/div/input[2]</value>
      <webElementGuid>bc20a6e8-cabb-4a0e-8969-e7783c8c0cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div[2]/div/input[2]</value>
      <webElementGuid>7b8ac57f-5d66-4e0c-a74a-614be21c9c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Name' and @name = 'payee-name' and @id = 'payee-name' and @type = 'text']</value>
      <webElementGuid>f43ea0e3-4ef5-46c7-b1ab-0e83feb24e3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
