<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AMEX CARD DETAILS_credit-card-number</name>
   <tag></tag>
   <elementGuidId>e80c4b29-b629-48fe-8116-2db0c7351df7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='amex-payee-card']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#amex-payee-card</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04ef74c1-c678-4db5-9091-f4a76784df8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>fb620cd2-2e22-4893-8933-fde083f609a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Credit Card Number</value>
      <webElementGuid>660abb0d-60bb-4eb7-a34e-ba2399f9f3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-payment</value>
      <webElementGuid>a3852bf3-7c39-4876-bffb-a79afc3ddaa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>ce959e29-8a30-48fd-912c-0be3d786050b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3c2c7677-402c-4dff-891b-00fb355c4e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>credit-card-number</value>
      <webElementGuid>c35b19b5-4f1d-40e6-b3bc-93b93ed931bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amex-payee-card</value>
      <webElementGuid>3461bdc6-38b0-4a77-8b3f-627d4edebd02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amex-payee-card&quot;)</value>
      <webElementGuid>702fea79-ecf8-42fc-9f18-be5fd36beb53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='amex-payee-card']</value>
      <webElementGuid>f1d8ca14-c1ca-4c7e-b78d-ecc69829c8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='amex-payment-form']/input</value>
      <webElementGuid>35bda957-cf2e-4bf2-aafd-f49fcaed4a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/input</value>
      <webElementGuid>a47d5564-53fc-4a0c-a8b0-498b3a83eae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Credit Card Number' and @type = 'tel' and @name = 'credit-card-number' and @id = 'amex-payee-card']</value>
      <webElementGuid>e029e26a-5102-4d0e-a828-b908aa1d71c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
