<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Agree</name>
   <tag></tag>
   <elementGuidId>842a2484-8ef9-4582-a1cf-718a600549a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rating_confirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='rating_confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aeba9918-26b0-434e-8bea-5a59b8b6c41b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button form-control mid-wide bg-red inline</value>
      <webElementGuid>57d727bd-fc06-4d84-9220-11e6fee110b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rating_confirm</value>
      <webElementGuid>9389bdba-0153-4ada-8b1b-01af43bc848f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agree</value>
      <webElementGuid>75d8db0e-69f8-4a4e-a14d-9f24eeb3373b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rating_confirm&quot;)</value>
      <webElementGuid>d7112de7-6f72-48c0-9ba8-5d0a1d751b9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='rating_confirm']</value>
      <webElementGuid>bca68443-6abf-403d-bfe9-5114d2ac5604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup-rating-warning']/div[2]/div/div/div[3]/a</value>
      <webElementGuid>3c044f89-2471-43b1-bcb9-a4f3cf768891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Agree')]</value>
      <webElementGuid>f336b583-a18c-4586-a549-3cdd6b27bfd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IMPORTANT PLEASE READ'])[1]/following::a[1]</value>
      <webElementGuid>2451c5fc-df9a-42ea-8d32-085910ab9fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NC16'])[1]/following::a[1]</value>
      <webElementGuid>9f7101fa-c2d9-4408-9950-d6ddf454bea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exit'])[1]/preceding::a[1]</value>
      <webElementGuid>54d40849-c4ff-486c-9b1f-17bce0160ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Different Rows of Seats'])[1]/preceding::a[2]</value>
      <webElementGuid>cd145052-c24b-4206-8e1b-7fd759be798b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agree']/parent::*</value>
      <webElementGuid>a7e223f7-2210-4a50-8640-77aa243f1c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div[2]/div/div/div[3]/a</value>
      <webElementGuid>d2fdf7a5-48b6-45d4-b629-02ae68f0ec11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'rating_confirm' and (text() = 'Agree' or . = 'Agree')]</value>
      <webElementGuid>fa49052d-8d14-45c0-9d6f-f0ba957fedc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
