<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Exit</name>
   <tag></tag>
   <elementGuidId>150348bc-b621-4d3b-8bc0-e907fd70e984</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#popup-rating-warning > div.popup-float-wrapper.popup-alert > div.popup-wrapper > div.popup-inner > div.popup-control > a.button.form-control.mid-wide.bg-red.inline.decline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popup-rating-warning']/div[2]/div/div/div[3]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d44127ee-9b65-41e2-a1f8-fcde9ef7d9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button form-control mid-wide bg-red inline decline</value>
      <webElementGuid>5cdef4e6-5123-4fec-bf8f-2ac5fc0d9bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Showtimes</value>
      <webElementGuid>ed07ec11-751b-4553-9d20-31daaf3978aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Exit</value>
      <webElementGuid>fdaa5631-1118-4d9c-9fe0-87a4fc634e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup-rating-warning&quot;)/div[@class=&quot;popup-float-wrapper popup-alert&quot;]/div[@class=&quot;popup-wrapper&quot;]/div[@class=&quot;popup-inner&quot;]/div[@class=&quot;popup-control&quot;]/a[@class=&quot;button form-control mid-wide bg-red inline decline&quot;]</value>
      <webElementGuid>a13e5ebf-ab0a-4d22-9dab-c4390a4d027c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup-rating-warning']/div[2]/div/div/div[3]/a[2]</value>
      <webElementGuid>01403726-6404-4998-9d61-a329a57d5b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Exit')]</value>
      <webElementGuid>555bdb81-9ad8-4075-8baf-bdd24371d9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agree'])[1]/following::a[1]</value>
      <webElementGuid>59a93c7d-17ca-423b-bac1-a25111abc15b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IMPORTANT PLEASE READ'])[1]/following::a[2]</value>
      <webElementGuid>b22e6534-a95b-43cb-999c-10ea80ecfc12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Different Rows of Seats'])[1]/preceding::a[1]</value>
      <webElementGuid>b38bb1d6-359d-4d68-9c48-d4daf0e9886b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceed'])[1]/preceding::a[2]</value>
      <webElementGuid>828be35c-32d5-4dca-9c89-0e0144a06580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Exit']/parent::*</value>
      <webElementGuid>ea590d46-bd0d-4fac-8f09-ce0919cd3841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/Showtimes')])[2]</value>
      <webElementGuid>199feffd-eff0-444e-a75a-95e209e10f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div[2]/div/div/div[3]/a[2]</value>
      <webElementGuid>26afa6a2-761d-42e9-982d-6007b64dbcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Showtimes' and (text() = 'Exit' or . = 'Exit')]</value>
      <webElementGuid>38178c69-5fdb-46e2-8656-6b890d997b73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
