<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_NC16</name>
   <tag></tag>
   <elementGuidId>0225e1b4-3188-4060-96d4-04846a5dcbb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.popup-headline.rating-heading > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popup-rating-warning']/div[2]/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dce895a1-7603-4446-8487-ce59835ad0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NC16</value>
      <webElementGuid>7c57a499-3e48-4caa-a732-c70d1ea2c1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup-rating-warning&quot;)/div[@class=&quot;popup-float-wrapper popup-alert&quot;]/div[@class=&quot;popup-wrapper&quot;]/div[@class=&quot;popup-inner&quot;]/div[@class=&quot;popup-headline rating-heading&quot;]/span[1]</value>
      <webElementGuid>76f4a273-790f-4761-ab3e-58a5035377ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup-rating-warning']/div[2]/div/div/div/span</value>
      <webElementGuid>e7d176c1-dcab-4315-901f-befb29e0f904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[5]/following::span[1]</value>
      <webElementGuid>55525bce-2ca7-48a6-b57f-0c725abcf385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vaccinated Only Hall'])[1]/following::span[1]</value>
      <webElementGuid>43efcbcb-4d10-49da-a749-e779431db4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IMPORTANT PLEASE READ'])[1]/preceding::span[2]</value>
      <webElementGuid>9b111af9-b282-4eae-bf31-5b229497e706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agree'])[1]/preceding::span[2]</value>
      <webElementGuid>3a0c99ad-761a-4228-896a-7c8da41e0570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NC16']/parent::*</value>
      <webElementGuid>9b6b1478-1a18-4911-935e-b55c56cc8ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div[2]/div/div/div/span</value>
      <webElementGuid>3549382a-27b3-4f84-acb3-6ffc3dc3aa97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'NC16' or . = 'NC16')]</value>
      <webElementGuid>e641c128-d362-41e5-b14e-cfc44cfebf28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
