<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SHOWTIMES</name>
   <tag></tag>
   <elementGuidId>85a28342-b03d-45fb-88ca-0f11452f27be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topbar']/div/div/div/div/div/div/div[4]/form/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-custom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c4ea1f8-b8d0-4f27-9d5e-e0c1a35b5fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-custom</value>
      <webElementGuid>4dd638e9-4a0c-4c84-945e-e35d7c4c1645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formaction</name>
      <type>Main</type>
      <value>/showtimes</value>
      <webElementGuid>7f8f3691-9f9a-49c8-83ff-1880aa4f1f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            SHOWTIMES
                                        </value>
      <webElementGuid>7121015e-f987-4993-adf6-866418dadad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topbar&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 pad-right-40&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-sm-12 clearfix&quot;]/div[@class=&quot;list-inline pull-left m-a-0 func&quot;]/div[@class=&quot;col-md-3 showtimes-col&quot;]/form[1]/button[@class=&quot;btn btn-primary btn-custom&quot;]</value>
      <webElementGuid>d182dd02-48ba-4623-84cb-04e6dfdc60a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topbar']/div/div/div/div/div/div/div[4]/form/button</value>
      <webElementGuid>fb6a9cdf-ed19-42d4-9c4e-66cb3020bbe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>6bb02c6c-8bc3-4cc7-b95c-1599800be174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                                            SHOWTIMES
                                        ' or . = '
                                            SHOWTIMES
                                        ')]</value>
      <webElementGuid>63529065-a992-4eeb-8e9a-eb15140c5e56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
