<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SHOWTIMES</name>
   <tag></tag>
   <elementGuidId>85a28342-b03d-45fb-88ca-0f11452f27be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-custom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/div[1]/div[1]/div[1]/div/div/div/div/div[1]/div/div[4]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3791cfc7-e5a9-4897-bfb2-a40386a06201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-custom</value>
      <webElementGuid>11c3e8b4-4e82-4304-b0a5-6862a092256f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formaction</name>
      <type>Main</type>
      <value>/showtimes</value>
      <webElementGuid>70ba1d7a-487e-4f81-b245-2ddbe0ec4cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            SHOWTIMES
                                        </value>
      <webElementGuid>cf82d1b6-a5cc-4cbf-ac43-125748951db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topbar&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 pad-right-40&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-sm-12 clearfix&quot;]/div[@class=&quot;list-inline pull-left m-a-0 func&quot;]/div[@class=&quot;col-md-3 showtimes-col&quot;]/form[1]/button[@class=&quot;btn btn-primary btn-custom&quot;]</value>
      <webElementGuid>1b4ec3ed-bd72-4fba-9ed0-0787cbc22203</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topbar']/div/div/div/div/div/div/div[4]/form/button</value>
      <webElementGuid>b0cf0724-5dfd-4aea-80ef-04998c57bd6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>d112fbd1-7e3a-4eaf-a833-2a43911939c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                                            SHOWTIMES
                                        ' or . = '
                                            SHOWTIMES
                                        ')]</value>
      <webElementGuid>98cc31df-6ead-40be-8dd7-8ac81b0cae02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
