<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Quantity of Addon</name>
   <tag></tag>
   <elementGuidId>551c4ce2-7a39-4dbe-a5a5-ce8a786c3745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addOnBreakdownSelection > div > div.col-md-4.col-sm-6.col-xs-6.right-text > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]/div[9]/div[4]/div[4]/div/div[2]/div/div/div/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e55b1cdd-f396-4ff6-9eb4-2db9c9aadcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ee922cba-49eb-44e8-add9-90dba1574a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addOnBreakdownSelection&quot;)/div[1]/div[@class=&quot;col-md-4 col-sm-6 col-xs-6 right-text&quot;]/p[1]</value>
      <webElementGuid>e930d331-8633-4ecf-b1a1-080612422a94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addOnBreakdownSelection']/div/div[2]/p</value>
      <webElementGuid>079e651b-b7fc-4e51-903e-d4ba6a24834a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD-ONS'])[1]/following::p[2]</value>
      <webElementGuid>dc377ad8-aa29-4517-971b-432cca9c58dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROMOS'])[2]/following::p[4]</value>
      <webElementGuid>fce06c9d-85cf-4a93-826b-941d5df27c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click on the image to select quantity of combo to purchase.'])[1]/preceding::p[2]</value>
      <webElementGuid>eccc5c27-6d24-4c94-a758-afc213687fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SK-LRGCOM'])[1]/preceding::p[2]</value>
      <webElementGuid>7022826b-9a45-4ae3-bad4-31534e6bdbb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/p</value>
      <webElementGuid>047c232f-cddb-4a77-812c-92d628f3c44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '1' or . = '1')]</value>
      <webElementGuid>44bfe5a6-4b97-4509-b0bb-71f53ce95d14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
