<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Regular Popcorn add</name>
   <tag></tag>
   <elementGuidId>b6822dc3-443e-4d8d-9372-8d0198d25afb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='concessions_list']/div[3]/div/div[2]/div/i[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>15a63886-f36d-4073-b4a5-313c8a184e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>c5d2efe7-22c2-4f9e-8db6-8f64c170e6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;concessions_list&quot;)/div[@class=&quot;item COMBPACK&quot;]/div[@class=&quot;item-add&quot;]/div[@class=&quot;item-option&quot;]/div[@class=&quot;item-qty&quot;]/i[@class=&quot;fa fa-plus&quot;]</value>
      <webElementGuid>2dde438d-ccbe-4ba0-aaf2-3003cba546d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='concessions_list']/div[3]/div/div[2]/div/i[2]</value>
      <webElementGuid>3ae6421d-9e6d-4502-9a25-9a03b82b94e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/i[2]</value>
      <webElementGuid>bf24287e-4087-4c42-b9f7-b059a01ac5ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
