<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_OK</name>
   <tag></tag>
   <elementGuidId>9ebe95a1-9321-4311-8dfd-2bb87ed4d643</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#seatSelectionSpacing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='seatSelectionSpacing']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8ba9bee6-621f-4908-be79-74448c726755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button form-control mid-wide bg-red inline</value>
      <webElementGuid>64caeff5-0f74-4181-b13f-1f62f45ae2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>seatSelectionSpacing</value>
      <webElementGuid>1591401a-e892-4ae6-a97b-0e752ca91517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>79393032-bd9a-4725-bd8b-3b2829a2001c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;seatSelectionSpacing&quot;)</value>
      <webElementGuid>bc76974b-8d9e-4272-8097-960eca91f78b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='seatSelectionSpacing']</value>
      <webElementGuid>9b50dea7-2012-4d53-bde4-dfbe61c18dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup-seat-selection-incorrect']/div[2]/div/div/div[3]/a</value>
      <webElementGuid>0a554874-9729-4357-8f61-654372695416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'OK')])[3]</value>
      <webElementGuid>45684965-b81c-4c71-bf1c-1da447ee2d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seat Selection Invalid'])[3]/following::a[1]</value>
      <webElementGuid>2c1e3799-ef0b-4c29-8ca6-214bbaff0150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[2]/following::a[2]</value>
      <webElementGuid>ff03582e-d653-4868-bc34-c75dad85497b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seat Selection Invalid'])[4]/preceding::a[2]</value>
      <webElementGuid>ce863325-87e0-4ab8-bb4b-b7c3354cf02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[4]/preceding::a[2]</value>
      <webElementGuid>da2d82c2-383b-434c-9880-803f91f8560b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div[2]/div/div/div[3]/a</value>
      <webElementGuid>64768ea1-4d76-4b37-bf9f-0f3904b20884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'seatSelectionSpacing' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>fe053600-e4a0-4be0-b44f-6adddbbbfc02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
