<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Imax_Menu</name>
   <tag></tag>
   <elementGuidId>bba4433a-dff2-4d16-99ca-fef2ab5c615b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.img-responsive.sprite-mobile-nav-imax.mar-left-35</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar']/div[3]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a66f2de3-e716-4688-8bf6-c82ccdada6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive sprite-mobile-nav-imax mar-left-35</value>
      <webElementGuid>9370105c-7892-4304-84f1-26729b97a316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/div[@class=&quot;imax&quot;]/a[1]/div[@class=&quot;img-responsive sprite-mobile-nav-imax mar-left-35&quot;]</value>
      <webElementGuid>027d0df3-0ade-4584-beed-70632e07b28e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar']/div[3]/a/div</value>
      <webElementGuid>31177c4f-f436-4863-a171-95ad754410c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div</value>
      <webElementGuid>cf1358ca-f906-4b6d-9373-54f97668a669</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
