<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SAFRA LOGIN</name>
   <tag></tag>
   <elementGuidId>1bd5e18e-60b1-4558-8492-df68ca9dc74e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.sidebar-item-menu.clearfix.show-for-desktop-only > a > span.mar-left-30</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar']/div[8]/ul/li[8]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8be09ef5-aae6-4da9-aa88-ab99908aecdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mar-left-30</value>
      <webElementGuid>9292af32-1f32-42a7-ac78-611dbea2fa5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SAFRA LOGIN</value>
      <webElementGuid>d170fa64-6dee-48c9-8d4e-25674d048b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/div[@class=&quot;sidebar-menu&quot;]/ul[@class=&quot;list-unstyled&quot;]/li[@class=&quot;sidebar-item-menu clearfix show-for-desktop-only&quot;]/a[1]/span[@class=&quot;mar-left-30&quot;]</value>
      <webElementGuid>e84bbabc-61d0-4bb4-aa00-a4958d2ff5cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar']/div[8]/ul/li[8]/a/span</value>
      <webElementGuid>f4b68418-6b09-4236-9f49-75e609830a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIVE CHAT'])[1]/preceding::span[1]</value>
      <webElementGuid>45599e7d-b4c0-4d87-85c8-efcd705e247b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUBSCRIBE'])[1]/preceding::span[2]</value>
      <webElementGuid>e21c7f96-ac4e-46ce-922a-29b7d78b69f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SAFRA LOGIN']/parent::*</value>
      <webElementGuid>ad936b7d-03f6-42ae-8c94-aa096778e8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a/span</value>
      <webElementGuid>fcda7759-0c6c-4828-a7e9-80cbf90d7fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'SAFRA LOGIN' or . = 'SAFRA LOGIN')]</value>
      <webElementGuid>45081681-e113-4a79-aced-a41644946bd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
