<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancel</name>
   <tag></tag>
   <elementGuidId>ce4b696d-6a55-46b4-a9c2-94c9d87aa2aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment-form > a.bt-a-mybutton.bt-bg-black.button-cancel-book</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;payment-form&quot;]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b0f4a9bc-3bd9-4c8b-b133-19b9100a5d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bt-a-mybutton bt-bg-black button-cancel-book</value>
      <webElementGuid>c3a3ad58-a959-4f55-a878-8a3448a2e1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>39ac909a-8e9d-4d8b-8c11-c6428fc532e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-form&quot;)/a[@class=&quot;bt-a-mybutton bt-bg-black button-cancel-book&quot;]</value>
      <webElementGuid>b5037870-b0a7-446c-818d-c56e2e89604e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-form']/a</value>
      <webElementGuid>e0346397-5376-4d12-90f2-82f6c2f3b84d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Cancel')])[2]</value>
      <webElementGuid>56ca0f7b-47cd-443a-b8a0-20a57749003f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security code'])[1]/following::a[1]</value>
      <webElementGuid>b58c9d93-e67b-48c7-9f65-509608338f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiry date'])[1]/following::a[1]</value>
      <webElementGuid>6537e722-39aa-4770-90da-a6bf5162e24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shaw Theatres Lido'])[2]/preceding::a[1]</value>
      <webElementGuid>9d53ba98-0205-423e-b578-56c1f2a5d3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms and conditions of use'])[2]/preceding::a[1]</value>
      <webElementGuid>f366cda8-06ec-4359-a05a-5e505953dbf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/a</value>
      <webElementGuid>16c7d149-c5e2-4f9a-bb9f-363319105e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>5bf31bed-9fc2-49b4-8507-d3178de7c6b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
