<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PAY</name>
   <tag></tag>
   <elementGuidId>76a50ba9-d2b7-4b20-ba0c-2da85bc1b5bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pay-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pay-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9afa03bf-fe33-4945-86e3-a1ea63e91c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pay-button</value>
      <webElementGuid>a4a3cf84-f730-488f-b32a-60a761e4a34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        PAY
                    </value>
      <webElementGuid>5e061a23-c80d-4c00-80e7-bc3cf6f5a9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pay-button&quot;)</value>
      <webElementGuid>c20f47e5-8d64-4ac8-b899-72f2e784e5ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pay-button']</value>
      <webElementGuid>b220d7f5-7732-4873-9610-327db6ec87b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-form']/button</value>
      <webElementGuid>c3a645eb-b228-49d7-bfdb-b334b7d88e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms and conditions of use'])[2]/following::button[1]</value>
      <webElementGuid>c0a729c5-11bd-48ca-9040-070a2f3ef5b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shaw Theatres Jewel'])[2]/following::button[1]</value>
      <webElementGuid>270a36d8-92a5-4951-9a7e-192218ac814a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seat Unavailable'])[1]/preceding::button[1]</value>
      <webElementGuid>65074d4a-2b1d-441e-9f95-7bc0836e6600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart Expired'])[1]/preceding::button[1]</value>
      <webElementGuid>88251097-3655-47b1-af3a-6d32b23685a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAY']/parent::*</value>
      <webElementGuid>efb2e3b0-d29d-4947-98a0-139d24b88c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/button</value>
      <webElementGuid>9bb45d2a-82a8-4686-b8d4-c8a8779c69e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pay-button' and (text() = '
                        PAY
                    ' or . = '
                        PAY
                    ')]</value>
      <webElementGuid>2a33d98f-9546-414d-b19e-587cfb356176</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
