<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_id(katalon-spy_elementInfoDiv)</name>
   <tag></tag>
   <elementGuidId>7057cbfe-258e-4422-879c-3fb32bdbec04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#katalon-spy_elementInfoDiv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='katalon-spy_elementInfoDiv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c5fe9f09-e9aa-40f1-bf8b-7d34ddd8d8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>katalon-spy_elementInfoDiv</value>
      <webElementGuid>8ee1c1b5-d11a-4c48-b85d-1e0cb217b30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>id(&quot;katalon-spy_elementInfoDiv&quot;)</value>
      <webElementGuid>aed96465-f69a-4c62-9d89-c9e540697b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon-spy_elementInfoDiv&quot;)</value>
      <webElementGuid>3270a7a9-ccef-45a0-bae8-e82254fea8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VISA Payment/iframe_Security code_checkout-frames-cvv</value>
      <webElementGuid>888822bd-aa62-44d0-b1db-68396c255fe9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='katalon-spy_elementInfoDiv']</value>
      <webElementGuid>7819e6f3-253e-4bd6-b034-41fb1225db70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='katalon']/div</value>
      <webElementGuid>549feeec-359b-4012-9a9b-5714c861e20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='id(&quot;katalon-spy_elementInfoDiv&quot;)']/parent::*</value>
      <webElementGuid>c713d709-dcc1-4ee6-a5e4-39bfe4cfc631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>2dd6672a-cb17-47e8-bb60-8266bbe4a454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'katalon-spy_elementInfoDiv' and (text() = 'id(&quot;katalon-spy_elementInfoDiv&quot;)' or . = 'id(&quot;katalon-spy_elementInfoDiv&quot;)')]</value>
      <webElementGuid>1366abb4-b099-4622-aeaf-325ddb50fa08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
