<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Card number_checkout-frames-cardNumber</name>
   <tag></tag>
   <elementGuidId>0d469efc-4f70-4530-978c-f1a83500ca30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cardNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='cardNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>27f0cddc-2397-45a1-b799-e7e6dde66670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardNumber</value>
      <webElementGuid>ac5ce88d-1ab2-48fb-b5ba-100d257e7562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.checkout.com/framesv2/?v=2.25.8&amp;publicKey=pk_a47db18b-cd50-40e4-b0bc-1f07f0ed3382&amp;iOS=false&amp;schemeChoiceVariant=NONE&amp;isMultiFrame=true&amp;safari=false&amp;cardNumberPlaceholder=Visa%252FMC%2520Card%2520number&amp;expiryMonthPlaceholder=MM&amp;expiryYearPlaceholder=YY&amp;cvvPlaceholder=CVV&amp;element=card-number</value>
      <webElementGuid>0b9815e7-9af7-4c31-a2cf-c88b39485859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>checkout-frames-cardNumber</value>
      <webElementGuid>09213f95-8d7e-4340-928e-6d9d97452933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkout-frames-cardNumber</value>
      <webElementGuid>6a461e9c-4ca1-4dca-9bab-5bfd94caf511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>682fc4b1-5216-4634-8a6f-e156b8a97479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2af5be10-4629-4c35-87a3-91ee088b0061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardNumber&quot;)</value>
      <webElementGuid>5a1629fa-3a3d-4ee1-8b6c-0f165b844431</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='cardNumber']</value>
      <webElementGuid>ea162654-d50d-43bf-bd9c-311fbcee2593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-form']/div/div[2]/iframe</value>
      <webElementGuid>87efe814-b165-4adc-a0ed-81e07613cafd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>935301df-0191-464f-a678-f0f4ea46859d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'cardNumber' and @src = 'https://js.checkout.com/framesv2/?v=2.25.8&amp;publicKey=pk_a47db18b-cd50-40e4-b0bc-1f07f0ed3382&amp;iOS=false&amp;schemeChoiceVariant=NONE&amp;isMultiFrame=true&amp;safari=false&amp;cardNumberPlaceholder=Visa%252FMC%2520Card%2520number&amp;expiryMonthPlaceholder=MM&amp;expiryYearPlaceholder=YY&amp;cvvPlaceholder=CVV&amp;element=card-number' and @title = 'checkout-frames-cardNumber' and @name = 'checkout-frames-cardNumber']</value>
      <webElementGuid>eaa6139a-4404-40a0-b3cb-d159c099512f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
