<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Security code_checkout-frames-cvv</name>
   <tag></tag>
   <elementGuidId>45eb6944-d8fa-4e69-a086-3c849c9ab756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cvv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='cvv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2ce29502-e70f-47ec-b03b-6ef3d4a0ab61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cvv</value>
      <webElementGuid>202d7289-deae-4ac3-8271-6c07e4284846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.checkout.com/framesv2/?v=2.25.8&amp;publicKey=pk_a47db18b-cd50-40e4-b0bc-1f07f0ed3382&amp;iOS=false&amp;schemeChoiceVariant=NONE&amp;isMultiFrame=true&amp;safari=false&amp;cardNumberPlaceholder=Visa%252FMC%2520Card%2520number&amp;expiryMonthPlaceholder=MM&amp;expiryYearPlaceholder=YY&amp;cvvPlaceholder=CVV&amp;element=cvv</value>
      <webElementGuid>2955b1aa-22f8-4f41-83d6-eb0cc63785cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>checkout-frames-cvv</value>
      <webElementGuid>4d9d0f7e-70f0-4970-8c3c-7c74b191014b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkout-frames-cvv</value>
      <webElementGuid>4fd08022-743d-4621-8e1e-8f59a3ed8bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>4a3ea3a9-ca17-468b-bd1b-8858564f472d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5a0b405a-9cce-43ac-b9bc-77869697c8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cvv&quot;)</value>
      <webElementGuid>d1e61556-cd4a-4c16-ada1-322acbfeae62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='cvv']</value>
      <webElementGuid>1dee1de5-9760-432e-8162-39d3a884dffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-form']/div[2]/div[2]/div/div[2]/iframe</value>
      <webElementGuid>c7682df8-cbcc-4c82-a1f0-df22d19acf13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/iframe</value>
      <webElementGuid>30b4a5a0-cbe6-470d-aba5-ec0c99b4d595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'cvv' and @src = 'https://js.checkout.com/framesv2/?v=2.25.8&amp;publicKey=pk_a47db18b-cd50-40e4-b0bc-1f07f0ed3382&amp;iOS=false&amp;schemeChoiceVariant=NONE&amp;isMultiFrame=true&amp;safari=false&amp;cardNumberPlaceholder=Visa%252FMC%2520Card%2520number&amp;expiryMonthPlaceholder=MM&amp;expiryYearPlaceholder=YY&amp;cvvPlaceholder=CVV&amp;element=cvv' and @title = 'checkout-frames-cvv' and @name = 'checkout-frames-cvv']</value>
      <webElementGuid>c9ab0d34-c696-424d-8a34-51579bb974b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
