<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Expiry date_checkout-frames-expiryDate</name>
   <tag></tag>
   <elementGuidId>5c1be8e4-2f8f-4e4b-b91c-84cf668c0ad5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expiryDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='expiryDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>65d03923-d62a-4e7b-9b3d-f2f9da9ed19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expiryDate</value>
      <webElementGuid>94f532cb-1084-4dbe-a0e2-c69d640d5bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.checkout.com/framesv2/?v=2.25.8&amp;publicKey=pk_a47db18b-cd50-40e4-b0bc-1f07f0ed3382&amp;iOS=false&amp;schemeChoiceVariant=NONE&amp;isMultiFrame=true&amp;safari=false&amp;cardNumberPlaceholder=Visa%252FMC%2520Card%2520number&amp;expiryMonthPlaceholder=MM&amp;expiryYearPlaceholder=YY&amp;cvvPlaceholder=CVV&amp;element=expiry-date</value>
      <webElementGuid>00c80e26-5199-4371-80cb-2e54111bf351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>checkout-frames-expiryDate</value>
      <webElementGuid>82672c32-c6a6-44ef-ae8a-e866789ebee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkout-frames-expiryDate</value>
      <webElementGuid>f541c409-ce28-4ba6-bb99-66cf7e50e2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>aa4ddf8e-5d0a-41b9-832f-2459e22bc05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5f35686a-4bbd-4f4e-abff-e2b71bdfe0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expiryDate&quot;)</value>
      <webElementGuid>4034f1d5-e04f-4138-bd37-2b8c1d05f430</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='expiryDate']</value>
      <webElementGuid>e75d8e3f-afea-4c3e-942f-b132fb54ffa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-form']/div[2]/div/div/div[2]/iframe</value>
      <webElementGuid>a2935fe5-f131-4c6f-aa84-ae3d14256684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/iframe</value>
      <webElementGuid>7e69ed81-86f9-49d8-a75a-f2119a5bfb8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'expiryDate' and @src = 'https://js.checkout.com/framesv2/?v=2.25.8&amp;publicKey=pk_a47db18b-cd50-40e4-b0bc-1f07f0ed3382&amp;iOS=false&amp;schemeChoiceVariant=NONE&amp;isMultiFrame=true&amp;safari=false&amp;cardNumberPlaceholder=Visa%252FMC%2520Card%2520number&amp;expiryMonthPlaceholder=MM&amp;expiryYearPlaceholder=YY&amp;cvvPlaceholder=CVV&amp;element=expiry-date' and @title = 'checkout-frames-expiryDate' and @name = 'checkout-frames-expiryDate']</value>
      <webElementGuid>1ef4ea4a-0aab-4ead-8eef-3b3ac97cf429</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
