<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , checkout-frames-card-number, , ))_cardnumber</name>
   <tag></tag>
   <elementGuidId>e0c43f39-a733-4821-ac0d-8abfbdce3c82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkout-frames-card-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkout-frames-card-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7a514e5-f15c-44f1-b6e1-be7fc3bd6e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-number field card-number--hover card-number--focus</value>
      <webElementGuid>5eaa8518-7ab2-444f-8e6d-5b476edc2733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkout-frames-card-number</value>
      <webElementGuid>a281a476-48fa-4d61-a5fc-443c8f748c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardnumber</value>
      <webElementGuid>6e264a81-6024-4a13-beaa-a51ffa0acbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>0b5334c6-5436-4132-a528-704f2e887a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-number</value>
      <webElementGuid>c3e79e00-3668-4e85-b81b-9c65e719c095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d155de7d-9e1a-4ae6-bb5d-c6f6d9123500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f12a1fb2-6072-48b2-86f2-efcf10b94a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Visa/MC Card number</value>
      <webElementGuid>6c673e87-6f21-484e-b153-76dcc90f9034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Visa/MC Card number</value>
      <webElementGuid>773d830c-0c2b-4a3a-a51b-f3bfe1959311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>Visa/MC Card number</value>
      <webElementGuid>dd5cc893-0b5a-4e58-94e5-87c1fd948f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>62d8548c-7d06-4362-b45d-d0ce1fefb46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-frames-card-number&quot;)</value>
      <webElementGuid>6db71ed1-84a4-4003-a434-14ce35ffb5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VISA Payment/iframe_Card number_checkout-frames-cardNumber</value>
      <webElementGuid>cfb60165-51e1-43e8-8ff2-a18deb7aa80c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkout-frames-card-number']</value>
      <webElementGuid>b720baba-8ac2-4eac-a3ad-5b4451146a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frames-element-card-number']/input[2]</value>
      <webElementGuid>c7bd3906-5654-43b3-9f1c-efe168e8bdb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>067d29e1-6589-4ec4-9554-b5ce3347025a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkout-frames-card-number' and @name = 'cardnumber' and @placeholder = 'Visa/MC Card number']</value>
      <webElementGuid>5ea3abaa-7322-4dc2-9ca3-f8257e374611</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
