<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , checkout-frames-expiry-date, , ))_exp-date</name>
   <tag></tag>
   <elementGuidId>7b724e67-d3ae-44c5-b6b0-97193f904326</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkout-frames-expiry-date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkout-frames-expiry-date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>379f942f-adac-4c19-a2d9-d109af856ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>expiry-date field expiry-date--hover expiry-date--focus</value>
      <webElementGuid>c97f58f9-d5eb-44b4-9389-ebf1091dbaa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkout-frames-expiry-date</value>
      <webElementGuid>ad1d2ae7-dca0-4653-bbbd-3fddf388f2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exp-date</value>
      <webElementGuid>8130afcf-60fe-43ff-a962-60c0842f8306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>8684f755-c223-4e60-9cfc-0a1c68055906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-exp</value>
      <webElementGuid>8baea624-fc3e-4187-a92f-31bca980094b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ea9c1248-6b5d-48bd-8f50-b315ad9aef86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d0d8f3ea-dcd0-49ae-ab68-b83cc0cad417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>MM/YY</value>
      <webElementGuid>caf2614d-91e9-4c39-9a91-7c090978b4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/YY</value>
      <webElementGuid>a0ca856c-d1cc-4003-b46d-5d4833bcb53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>MM/YY</value>
      <webElementGuid>c13727ac-4b6a-4a12-bdd8-409f9865c79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>01126763-c3ba-47c7-97d1-f4ab02699e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-frames-expiry-date&quot;)</value>
      <webElementGuid>7953bceb-86a6-49a7-a172-ebccb818310d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/VISA Payment/iframe_Expiry date_checkout-frames-expiryDate</value>
      <webElementGuid>0984fbfa-47b1-48d5-9b9c-1570e28ab0ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkout-frames-expiry-date']</value>
      <webElementGuid>cec48005-e76d-4aec-9930-fa004ce35ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frames-element-expiry-date']/input[2]</value>
      <webElementGuid>7946c979-856d-40ae-8b1f-1b229e76be82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>df9d2ccd-8096-4540-8757-ee3f91c02a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkout-frames-expiry-date' and @name = 'exp-date' and @placeholder = 'MM/YY']</value>
      <webElementGuid>098390ec-c5a5-4fc8-8e98-d9fe6231c1ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
