<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amex_payee-name</name>
   <tag></tag>
   <elementGuidId>62e9fea2-df78-45bb-96e3-1b74dace3364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payee-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payee-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21427c7c-73d4-4312-b1ea-1293e339ddea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>d3df2358-38d1-4ed8-869f-b416144714ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-payment</value>
      <webElementGuid>eac5fa8e-21d2-4f1e-ace1-f166b3b8a864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payee-name</value>
      <webElementGuid>30cd7ed4-a590-4ba9-b04f-ef41f5d7147c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payee-name</value>
      <webElementGuid>3f9d11a5-8b2f-47bb-bdb9-9de3b13c22c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>084694f9-3e6a-4967-8855-869442c5502e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20d53d61-72ca-445d-968d-09bd2b19e31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payee-name&quot;)</value>
      <webElementGuid>b0906deb-20a4-43ab-a593-08d9fc451457</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payee-name']</value>
      <webElementGuid>0a67f5a6-a934-4dd4-8476-ead7aa755edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personal-details']/div/input[2]</value>
      <webElementGuid>699f999e-4630-4c07-bf10-b12eaedcb28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div[2]/div/input[2]</value>
      <webElementGuid>05966d0e-d782-4c57-84e8-d22316cc13b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Name' and @name = 'payee-name' and @id = 'payee-name' and @type = 'text']</value>
      <webElementGuid>19542f3e-a9e5-42c8-a7f8-87e819dd7057</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
