<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose your payment method_gender</name>
   <tag></tag>
   <elementGuidId>39b98624-d23f-416e-927f-3570c8230002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#normal-payment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='normal-payment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ce0fd09-c711-4c5c-ac77-fac5568f7be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d2932f22-daeb-4f3d-b7a5-c8519fe2a333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>normal-payment</value>
      <webElementGuid>d7afc8dc-c03c-4599-8f0a-45977caa30f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>ad8100b2-ed73-4164-af5f-47ec68738dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>other</value>
      <webElementGuid>b5fb832a-fd28-4c95-acad-17be4022f79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;normal-payment&quot;)</value>
      <webElementGuid>a1058c24-9cdb-46ba-a8ff-1df296ccb53a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='normal-payment']</value>
      <webElementGuid>e7b1106a-89bd-40a8-98ae-9776e8b9c047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-payment-method']/input</value>
      <webElementGuid>f40161db-8fff-4319-9e68-d3b032ae8755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/input</value>
      <webElementGuid>9f866984-d8f2-4b69-a380-f751a1db30f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'normal-payment' and @name = 'gender']</value>
      <webElementGuid>b25071c0-464d-41c8-82a3-611c54ef905f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
