<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amex_payee-email</name>
   <tag></tag>
   <elementGuidId>5dd55b20-db3a-401c-949b-a04ac52e89b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payee-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payee-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68170715-1bca-466d-8a7c-017c35e82f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>666c94d2-ffdf-42de-a39b-c72bd327ec6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-payment</value>
      <webElementGuid>acfd9262-7ac7-41ff-9f62-660d83207045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payee-email</value>
      <webElementGuid>d9a2055c-03e4-4925-96b4-38945bd1fc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payee-email</value>
      <webElementGuid>0c35c2ce-35fa-4b06-b849-6014c0ad2cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>95590d7a-034b-48c3-9df6-6665ad2c8900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10ab76e4-bf74-43c2-9ef5-c5c374664b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payee-email&quot;)</value>
      <webElementGuid>d62346f2-aa27-488a-a9cd-887073fd4f17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payee-email']</value>
      <webElementGuid>119a6070-aad3-4d86-be55-5e0b9a48e150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personal-details']/div/input[3]</value>
      <webElementGuid>9fb92e0b-53ae-495c-9716-22373749400d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div[2]/div/input[3]</value>
      <webElementGuid>a0a8c769-28ec-4742-877d-adfbc0e908f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email' and @name = 'payee-email' and @id = 'payee-email' and @type = 'text']</value>
      <webElementGuid>b24026da-2322-474b-8d4c-9e9b01bfa97c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
