<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amex_payee-contact</name>
   <tag></tag>
   <elementGuidId>beaa62e3-7464-4b72-8b16-58f1bcbf07ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payee-contact</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payee-contact']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef024b77-122c-487d-801b-7a0dda74abb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contact Number</value>
      <webElementGuid>15ed04a8-212c-427b-a6d1-59850f4b02c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-payment numbers-only</value>
      <webElementGuid>432d43fd-94de-43c0-927b-6e818d5ab691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payee-contact</value>
      <webElementGuid>8a04cc5b-dd83-4e06-9d3a-97d668050e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payee-contact</value>
      <webElementGuid>d65b0067-5b1d-47d8-86a9-403a4801ac19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9a0372fa-a466-435e-8684-7ec352dedd7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd3e3205-a7c0-43a4-b633-a5b44045f552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payee-contact&quot;)</value>
      <webElementGuid>57a56626-3a46-49db-b4ed-29b0fe4b23ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payee-contact']</value>
      <webElementGuid>8a43d96e-39a3-4f98-bb74-68e91d196d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personal-details']/div/input[4]</value>
      <webElementGuid>38760829-eab4-4299-b309-e3ad2118e905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input[4]</value>
      <webElementGuid>f8c2a478-0e0f-4fde-8790-13fbca97a498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Contact Number' and @name = 'payee-contact' and @id = 'payee-contact' and @type = 'text']</value>
      <webElementGuid>9bb82fb8-3c66-440b-a58f-f81330ac6eaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
