<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select_Weekday Imax laser 1 ad 3 ch</name>
   <tag></tag>
   <elementGuidId>6881c6ea-010b-4335-bbbb-24f9ddbc0e96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='promo_overlay']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2120274e-80c2-4963-9733-31c971d69fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-code</name>
      <type>Main</type>
      <value>CA-IM-FAMILY</value>
      <webElementGuid>e54c2e3e-e67c-4b11-a7ab-09e4fa38aedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bundle-code</name>
      <type>Main</type>
      <value>BD-WD-IDL13</value>
      <webElementGuid>3abf8d0a-3c7e-4b40-8d02-b0993045e994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bt-a-promo bt-a-mybutton bt-bg-red conc-add-cart-btn btn_promotion_confirm_add_to_cart </value>
      <webElementGuid>b231232c-7959-4b48-b63a-bc6fcb8f98f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>b499d114-0f5a-4bff-8499-a4e948008b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promo_overlay&quot;)/div[@class=&quot;item item-promo&quot;]/a[@class=&quot;bt-a-promo bt-a-mybutton bt-bg-red conc-add-cart-btn btn_promotion_confirm_add_to_cart&quot;]</value>
      <webElementGuid>299d7142-a64b-43c9-a456-aa39fc3c0afb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='promo_overlay']/div/a</value>
      <webElementGuid>c6bc57b5-60b0-4823-885d-85c3cc4b0592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>9eb349a8-c110-434a-b845-7a14f93c6328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weekday IMAX Laser Digital Family (1 AD + 3 CH)'])[1]/following::a[1]</value>
      <webElementGuid>b6ec938d-fa52-45a6-b4d9-031c23463a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='here'])[2]/following::a[2]</value>
      <webElementGuid>52a89a0b-42d3-4238-bf9a-696a0f14a937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weekday IMAX Laser Digital Family (2 AD + 2 CH)'])[1]/preceding::a[1]</value>
      <webElementGuid>ac60aab3-5ff8-4e31-b591-2e4aedb35bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[3]/preceding::a[2]</value>
      <webElementGuid>d1eccf71-83e9-446d-8fc9-8267a43116e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/a</value>
      <webElementGuid>b7b20674-a031-45d5-9bc5-dc653ee6bca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>ac520869-405f-4f9b-9222-17f0f615bf40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
